[server]
headless = true
enableXsrfProtection = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#020617"
secondaryBackgroundColor = "#1E293B"
textColor = "#F1F5F9"
font = "sans serif"
